#!/bin/sh
#
# Prohibit messages that start with past tense.
#
# This is very naive implementation and only checks some pre-defined words.
# Note that comparison is case-sensitive.

declare -a words=("Fixed" "Added" "Changed" "Updated")

for word in "${words[@]}"
do
  if [[ $1 == $word* ]]
  then
    echo "Commit message can't start with word '$word'!"
    exit 1
  fi
done
