#!/bin/bash

declare -a hooks=("commit-msg" "pre-commit" "pre-push")

for hook in "${hooks[@]}"
do
    cp $hook ../.git/hooks/

    if [ $? == 1 ]; then
        printf "Something went wrong. Failed to install $hook hook\n"
        exit 1
    else
        printf "Installed $hook hook.\n"
    fi
done
