#!/bin/bash

### RUN PHP CODE SNIFFER AND ABORT ON ANY WARNING OR ERROR

printf "Running phpcs...\n"

OUTPUT=`git diff --name-only --cached --relative | grep '\.jsx\?$' | xargs phpcs --standard=ci/ruleset.xml visualcomposer/ && git diff --name-only --cached --relative | grep '\.jsx\?$' | xargs standard`

# Check last return code (#?).
printf "$OUTPUT\n"
if [ $? -ne 0 ]
then
	printf "Code style verification failed. Aborting Commit!\n"
	printf "$OUTPUT\n"
	exit 1
fi

exit 0