#!/bin/bash

### RUN PHPUNIT TESTS BEFORE PUSH

echo "Running phpunit tests...\n"

OUTPUT=`phpunit --configuration=ci/phpunit.xml`

# Check last return code (#?).
if [ $? -ne 0 ]
then
	# quotes preserve formatting
	echo "$OUTPUT\n"
	echo "ABORTING!!!\n"
	exit 1
fi

exit 0