#!/bin/bash

### RUN PHPUNIT TESTS BEFORE PUSH

printf "Running phpunit tests...\n"

OUTPUT=`phpunit --configuration=ci/phpunit.xml`

# Check last return code (#?).
if [ $? -ne 0 ]
then
	# quotes preserve formatting
	printf "$OUTPUT\n"
	printf "ABORTING!!!\n"
	exit 1
fi

exit 0