module.exports = {
  repo: 'git@gitlab.com:visual-composer-website-builder/builder.git',
  accountRepo: 'git@gitlab.com:visual-composer-website-builder/account.git',
  bundleElements: [
    'row',
    'column',
    'textBlock',
    'singleImage',
    'basicButton',
    'featureSection',
    'flickrImage',
    'googleFontsHeading',
    'googleMaps',
    'googlePlusButton',
    'heroSection',
    'icon',
    'imageGallery',
    'imageMasonryGallery',
    'instagramImage',
    'outlineButton',
    'pinterestPinit',
    'rawHtml',
    'facebookLike',
    'feature',
    'rawJs',
    'separator',
    'shortcode',
    'twitterButton',
    'twitterGrid',
    'twitterTimeline',
    'twitterTweet',
    'vimeoPlayer',
    'wpWidgetsCustom',
    'wpWidgetsDefault',
    'youtubePlayer',
    'faqToggle'
  ]
}